tree-root-file = "flake.nix"

[formatter.nix]
command = "nixfmt"
options = ["--width", "100"]
includes = ["*.nix"]

[formatter.lua]
command = "stylua"
includes = ["*.lua"]

[formatter.shell]
command = "shfmt"
options = ["-w", "-i", "2", "-ci"]
includes = ["*.sh"]

[formatter.markdown]
command = "prettier"
options = ["--write"]
includes = ["*.md", "*.markdown"]
